"""initial schema

Revision ID: 4415af868d9c
Revises: 
Create Date: 2026-07-23 12:41:26.779103
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.base  # custom GUID / UTCDateTime types


revision: str = '4415af868d9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_local_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_records',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('request_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('answer_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_records_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_user_id'), ['user_id'], unique=False)

    op.create_table('source_collections',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_collections_user_id'), ['user_id'], unique=False)

    op.create_table('subjects',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('sessions',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('saved', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sessions_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('sources',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('subject_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('collection_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('publication_date', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('stored_path', sa.String(length=1000), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('effective_date', sa.String(length=40), nullable=True),
    sa.Column('supersedes_source_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['source_collections.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_user_id'), ['user_id'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('source_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('passage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_source_id'), ['source_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_session_id'), ['session_id'], unique=False)

    op.create_table('question_queue',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('request_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('approved_source_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('claimed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_queue_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_queue_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_queue_user_id'), ['user_id'], unique=False)

    op.create_table('source_passages',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('source_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_passages', schema=None) as batch_op:
        batch_op.create_index('ix_passage_source_chunk', ['source_id', 'chunk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_passages_source_id'), ['source_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('session_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('message_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('request_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('audit_id', app.db.base.GUID(length=36), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('completed_stages', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model_identifier', sa.String(length=80), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_status'), ['status'], unique=False)

    op.create_table('claims',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('answer_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_answer_id'), ['answer_id'], unique=False)

    op.create_table('citations',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('claim_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('citation_number', sa.Integer(), nullable=False),
    sa.Column('source_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('passage_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['source_passages.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_claim_id'), ['claim_id'], unique=False)

    op.create_table('verification_results',
    sa.Column('id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('claim_id', app.db.base.GUID(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('verified_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_claim_id'), ['claim_id'], unique=True)

    # ### end Alembic commands ###

    # Full-text search index (SQLite only; Postgres uses tsvector instead).
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            "CREATE VIRTUAL TABLE IF NOT EXISTS passage_fts "
            "USING fts5(passage_id UNINDEXED, source_id UNINDEXED, text)"
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TABLE IF EXISTS passage_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_claim_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_claim_id'))

    op.drop_table('citations')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_answer_id'))

    op.drop_table('claims')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_status'))
        batch_op.drop_index(batch_op.f('ix_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_answers_request_id'))

    op.drop_table('answers')
    with op.batch_alter_table('source_passages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_passages_source_id'))
        batch_op.drop_index('ix_passage_source_chunk')

    op.drop_table('source_passages')
    with op.batch_alter_table('question_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_queue_user_id'))
        batch_op.drop_index(batch_op.f('ix_question_queue_status'))
        batch_op.drop_index(batch_op.f('ix_question_queue_session_id'))
        batch_op.drop_index(batch_op.f('ix_question_queue_request_id'))

    op.drop_table('question_queue')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_session_id'))

    op.drop_table('messages')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_source_id'))

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_user_id'))
        batch_op.drop_index(batch_op.f('ix_sources_subject_id'))
        batch_op.drop_index(batch_op.f('ix_sources_state'))
        batch_op.drop_index(batch_op.f('ix_sources_content_hash'))

    op.drop_table('sources')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_user_updated')
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_user_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('source_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_collections_user_id'))

    op.drop_table('source_collections')
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_request_id'))

    op.drop_table('audit_records')
    op.drop_table('users')
    # ### end Alembic commands ###
